// Validating the engine against PyTorch.
//
// Numerical gradient checking (tests/test_*.cpp) shows that the engine is
// consistent with itself. This shows something stronger: that it agrees with the
// industry's reference implementation.
//
// The files in tests/fixtures/ are generated by tools/generate_reference.py with
// PyTorch and are committed, so these tests run in CI without needing Python.
// Each one carries the inputs, the weights, the output gradient used, the
// expected output and every expected gradient.

#include "test_support.hpp"

#include "engine/serialize.hpp"

#include <map>
#include <string>

using namespace testing;

namespace {

#ifndef ENGINE_FIXTURE_DIR
#define ENGINE_FIXTURE_DIR "tests/fixtures"
#endif

// float32 accumulates in a different order in PyTorch than here, so exact
// equality is neither reachable nor desirable. 1e-4 absolute, on values of order
// one, leaves ample room to catch a derivative that was written wrongly.
constexpr float kTolerance = 1e-4f;

using Fixture = std::map<std::string, Tensor>;

Fixture load(const std::string& name) {
    Fixture fixture;
    const std::string path = std::string(ENGINE_FIXTURE_DIR) + "/" + name + ".bin";
    for (auto& entry : engine::load_tensors(path)) {
        fixture.emplace(entry.first, entry.second);
    }
    return fixture;
}

const Tensor& get(const Fixture& fixture, const std::string& key) {
    auto it = fixture.find(key);
    if (it == fixture.end()) {
        throw std::runtime_error("El fixture does not contain '" + key + "'.");
    }
    return it->second;
}

// Compares against PyTorch reporting the maximum deviation, which is the useful
// figure when something fails: it says whether it is float noise or a real error.
void check_matches(const Tensor& actual, const Tensor& expected, const std::string& what,
                   float tolerance = kTolerance) {
    if (actual.shape() != expected.shape()) {
        check(false, what + " (forma " + actual.shape_str() + ", PyTorch da " +
                         expected.shape_str() + ")");
        return;
    }
    float max_diff = 0.0f;
    for (size_t i = 0; i < actual.size(); ++i) {
        max_diff = std::max(max_diff, std::fabs(actual.data()[i] - expected.data()[i]));
    }
    ++g_checks;
    if (max_diff <= tolerance) {
        std::cout << "  [ ok ] " << what << " (largest deviation " << std::scientific
                  << std::setprecision(2) << max_diff << std::defaultfloat << ")\n";
    } else {
        ++g_failures;
        std::cout << "  [FAIL] " << what << " (largest deviation " << max_diff << " > " << tolerance
                  << ")\n";
    }
}

// Copies the fixture's weights into an engine parameter, keeping the
// requires_grad the layer needs in order to accumulate gradient.
void set_param(Tensor& param, const Tensor& source) {
    if (param.shape() != source.shape()) {
        throw std::runtime_error("The fixture's weight has shape " + source.shape_str() +
                                 " and the layer expects " + param.shape_str() + ".");
    }
    std::copy_n(source.data(), source.size(), param.data());
    param.set_requires_grad(true);
    param.zero_grad();
}

Tensor input_of(const Fixture& fixture, const std::string& key) {
    Tensor t = get(fixture, key).detach();
    t.set_requires_grad(true);
    return t;
}

// ---------------------------------------------------------
// Tensor operations
// ---------------------------------------------------------

void test_matmul_cases() {
    section("PyTorch: matrix multiplication");

    for (const std::string& name : {"matmul", "matmul_batched", "matmul_shared"}) {
        Fixture f = load(name);
        Tensor a = input_of(f, "a");
        Tensor b = input_of(f, "b");

        Tensor out = a.matmul(b);
        check_matches(out, get(f, "output"), name + ": output");

        out.backward(get(f, "grad_output"));
        check_matches(a.grad(), get(f, "grad.a"), name + ": gradient of A");
        check_matches(b.grad(), get(f, "grad.b"), name + ": gradient of B");
    }
}

void test_softmax_cases() {
    section("PyTorch: softmax");

    for (const std::string& name : {"softmax", "softmax_3d"}) {
        Fixture f = load(name);
        Tensor x = input_of(f, "input");

        Tensor out = x.softmax();
        check_matches(out, get(f, "output"), name + ": output");

        out.backward(get(f, "grad_output"));
        check_matches(x.grad(), get(f, "grad.input"), name + ": gradient");
    }
}

void test_activation_cases() {
    section("PyTorch: activaciones");

    nn::ReLU relu;
    nn::Sigmoid sigmoid;
    nn::Tanh tanh_layer;
    nn::GELU gelu;

    const std::pair<std::string, nn::Module*> cases[] = {
        {"act_relu", &relu},
        {"act_sigmoid", &sigmoid},
        {"act_tanh", &tanh_layer},
        {"act_gelu", &gelu},
    };

    for (const auto& entry : cases) {
        Fixture f = load(entry.first);
        Tensor x = input_of(f, "input");

        Tensor out = entry.second->forward(x);
        check_matches(out, get(f, "output"), entry.first + ": output");

        out.backward(get(f, "grad_output"));
        check_matches(x.grad(), get(f, "grad.input"), entry.first + ": gradient");
    }
}

void test_reduction_cases() {
    section("PyTorch: reductions along an axis");

    Fixture f = load("reductions");
    const std::tuple<std::string, size_t, const char*> cases[] = {
        {"sum0", 0, "sum"},
        {"sum1", 1, "sum"},
        {"mean1", 1, "mean"},
    };

    for (const auto& entry : cases) {
        const std::string tag = std::get<0>(entry);
        const size_t axis = std::get<1>(entry);
        const std::string op = std::get<2>(entry);

        Tensor x = input_of(f, "input");
        Tensor out = (op == "sum") ? x.sum(axis) : x.mean(axis);
        check_matches(out, get(f, "output." + tag), "reductions " + tag + ": output");

        out.backward(get(f, "grad_output." + tag));
        check_matches(x.grad(), get(f, "grad." + tag), "reductions " + tag + ": gradient");
    }

    Tensor xm = input_of(f, "input.max");
    Tensor out = xm.max(1);
    check_matches(out, get(f, "output.max1"), "reductions max1: output");
    out.backward(get(f, "grad_output.max1"));
    check_matches(xm.grad(), get(f, "grad.max1"), "reductions max1: gradient");
}

// ---------------------------------------------------------
// Layers
// ---------------------------------------------------------

void test_linear_cases() {
    section("PyTorch: dense layer");

    for (const std::string& name : {"linear", "linear_3d"}) {
        Fixture f = load(name);
        const size_t in_features = get(f, "weight").shape()[0];
        const size_t out_features = get(f, "weight").shape()[1];

        nn::Linear layer(in_features, out_features);
        set_param(layer.weight(), get(f, "weight"));
        set_param(layer.bias(), get(f, "bias"));

        Tensor x = input_of(f, "input");
        Tensor out = layer(x);
        check_matches(out, get(f, "output"), name + ": output");

        out.backward(get(f, "grad_output"));
        check_matches(x.grad(), get(f, "grad.input"), name + ": gradient of the input");
        check_matches(layer.weight().grad(), get(f, "grad.weight"),
                      name + ": gradient of the weight");
        check_matches(layer.bias().grad(), get(f, "grad.bias"), name + ": gradient of the bias");
    }
}

void test_conv_cases() {
    section("PyTorch: convolution and pooling");

    const std::tuple<std::string, size_t, size_t, size_t, size_t> cases[] = {
        {"conv2d_pad1", 3, 4, 1, 1},  // in, out, stride, padding
        {"conv2d_stride2", 1, 2, 2, 0},
    };

    for (const auto& entry : cases) {
        const std::string name = std::get<0>(entry);
        Fixture f = load(name);

        nn::Conv2d conv(std::get<1>(entry), std::get<2>(entry),
                        nn::Window2d(3, 3, std::get<3>(entry), std::get<4>(entry)));
        set_param(conv.weight(), get(f, "weight"));
        set_param(conv.bias(), get(f, "bias"));

        Tensor x = input_of(f, "input");
        Tensor out = conv(x);
        check_matches(out, get(f, "output"), name + ": output");

        out.backward(get(f, "grad_output"));
        check_matches(x.grad(), get(f, "grad.input"), name + ": gradient of the input");
        check_matches(conv.weight().grad(), get(f, "grad.weight"),
                      name + ": gradient of the kernel");
        check_matches(conv.bias().grad(), get(f, "grad.bias"), name + ": gradient of the bias");
    }

    Fixture f = load("maxpool2d");
    nn::MaxPool2d pool(2, 2);
    Tensor x = input_of(f, "input");
    Tensor out = pool(x);
    check_matches(out, get(f, "output"), "maxpool2d: output");
    out.backward(get(f, "grad_output"));
    check_matches(x.grad(), get(f, "grad.input"), "maxpool2d: gradient");
}

void test_layernorm_case() {
    section("PyTorch: LayerNorm");

    Fixture f = load("layernorm");
    nn::LayerNorm norm(8);
    set_param(norm.gamma(), get(f, "gamma"));
    set_param(norm.beta(), get(f, "beta"));

    Tensor x = input_of(f, "input");
    Tensor out = norm(x);
    check_matches(out, get(f, "output"), "layernorm: output");

    out.backward(get(f, "grad_output"));
    check_matches(x.grad(), get(f, "grad.input"), "layernorm: gradient of the input");
    check_matches(norm.gamma().grad(), get(f, "grad.gamma"), "layernorm: gradient of gamma");
    check_matches(norm.beta().grad(), get(f, "grad.beta"), "layernorm: gradient of beta");
}

void test_cross_entropy_case() {
    section("PyTorch: entropia cruzada");

    Fixture f = load("cross_entropy");
    Tensor logits = input_of(f, "logits");

    std::vector<size_t> targets;
    // The Tensor is held in a variable: walking get(f, "targets").data() directly
    // would leave the reference dangling, because the temporary dies before the loop
    // begins.
    const Tensor target_values = get(f, "targets");
    for (size_t i = 0; i < target_values.size(); ++i)
        targets.push_back(static_cast<size_t>(target_values.data()[i]));

    Tensor loss = nn::cross_entropy_loss(logits, targets);
    check_matches(loss, get(f, "output"), "cross_entropy: loss");

    loss.backward();
    check_matches(logits.grad(), get(f, "grad.logits"), "cross_entropy: gradient");
}

// ---------------------------------------------------------
// Attention
// ---------------------------------------------------------

void test_attention_cases() {
    section("PyTorch: attention");

    for (const std::string& name : {"attention", "attention_causal"}) {
        Fixture f = load(name);
        Tensor q = input_of(f, "q");
        Tensor k = input_of(f, "k");
        Tensor v = input_of(f, "v");

        const bool causal = (name == "attention_causal");
        Tensor mask;
        if (causal) mask = get(f, "mask");

        Tensor weights;
        Tensor out = nn::scaled_dot_product_attention(q, k, v, causal ? &mask : nullptr, &weights);

        check_matches(out, get(f, "output"), name + ": output");
        check_matches(weights, get(f, "weights"), name + ": attention weights");

        out.backward(get(f, "grad_output"));
        check_matches(q.grad(), get(f, "grad.q"), name + ": gradient of Q");
        check_matches(k.grad(), get(f, "grad.k"), name + ": gradient of K");
        check_matches(v.grad(), get(f, "grad.v"), name + ": gradient of V");
    }
}

void test_multihead_case() {
    section("PyTorch: multi-head attention");

    Fixture f = load("multihead_attention");
    nn::MultiHeadAttention mha(8, 2);

    // parameters() returns the four projections in order -- query, key, value and
    // output -- each with its weight and its bias.
    std::vector<Tensor> params = mha.parameters();
    const char* tags[] = {"query", "key", "value", "out"};
    for (size_t i = 0; i < 4; ++i) {
        set_param(params[i * 2], get(f, std::string("w.") + tags[i] + ".weight"));
        set_param(params[i * 2 + 1], get(f, std::string("w.") + tags[i] + ".bias"));
    }

    Tensor x = input_of(f, "input");
    Tensor out = mha(x);
    check_matches(out, get(f, "output"), "multihead: output");

    out.backward(get(f, "grad_output"));
    check_matches(x.grad(), get(f, "grad.input"), "multihead: gradient of the input");
    for (size_t i = 0; i < 4; ++i) {
        check_matches(params[i * 2].grad(), get(f, std::string("grad.") + tags[i] + ".weight"),
                      std::string("multihead: gradient of the weight ") + tags[i]);
        check_matches(params[i * 2 + 1].grad(), get(f, std::string("grad.") + tags[i] + ".bias"),
                      std::string("multihead: gradient of the bias ") + tags[i]);
    }
}

void test_transformer_block_case() {
    section("PyTorch: bloque Transformer completo");

    Fixture f = load("transformer_block");
    nn::TransformerBlock block(8, 2, 16);

    // parameters() walks norm1, norm2, the attention (query, key, value, output) and
    // the two dense layers, in that order.
    std::vector<Tensor> params = block.parameters();
    const char* names[] = {"norm1.gamma",  "norm1.beta", "norm2.gamma", "norm2.beta",
                           "query.weight", "query.bias", "key.weight",  "key.bias",
                           "value.weight", "value.bias", "out.weight",  "out.bias",
                           "ff1.weight",   "ff1.bias",   "ff2.weight",  "ff2.bias"};
    check(params.size() == 16, "the block exposes the 16 expected parameters");

    for (size_t i = 0; i < params.size(); ++i) {
        set_param(params[i], get(f, std::string("w.") + names[i]));
    }

    Tensor x = input_of(f, "input");
    Tensor out = block(x);
    check_matches(out, get(f, "output"), "transformer_block: output");

    out.backward(get(f, "grad_output"));
    check_matches(x.grad(), get(f, "grad.input"), "transformer_block: gradient of the input");
    for (size_t i = 0; i < params.size(); ++i) {
        check_matches(params[i].grad(), get(f, std::string("grad.") + names[i]),
                      std::string("transformer_block: gradient of ") + names[i]);
    }
}

// ---------------------------------------------------------
// Optimizadores
// ---------------------------------------------------------

// The whole trajectory is compared, not just the result: an error in Adam's bias
// correction can get the first step right and drift afterwards.
//
void test_optimizer_trajectories() {
    section("PyTorch: optimiser trajectories");

    {
        Fixture f = load("adam");
        Tensor w = input_of(f, "initial");
        Tensor target = get(f, "target");
        optim::Adam opt({w}, 0.1f);

        for (size_t step = 0; step < 10; ++step) {
            opt.zero_grad();
            Tensor diff = w - target;
            (diff * diff).mean().backward();
            opt.step();
            check_matches(w, get(f, "step." + std::to_string(step)),
                          "Adam: step " + std::to_string(step), 2e-4f);
        }
    }
    {
        Fixture f = load("sgd_momentum");
        Tensor w = input_of(f, "initial");
        Tensor target = get(f, "target");
        optim::SGD opt({w}, 0.05f, 0.9f);

        for (size_t step = 0; step < 10; ++step) {
            opt.zero_grad();
            Tensor diff = w - target;
            (diff * diff).mean().backward();
            opt.step();
            check_matches(w, get(f, "step." + std::to_string(step)),
                          "SGD with momentum: step " + std::to_string(step), 2e-4f);
        }
    }
}

}  // namespace

void run_reference_tests() {
    test_matmul_cases();
    test_softmax_cases();
    test_activation_cases();
    test_reduction_cases();
    test_linear_cases();
    test_conv_cases();
    test_layernorm_case();
    test_cross_entropy_case();
    test_attention_cases();
    test_multihead_case();
    test_transformer_block_case();
    test_optimizer_trajectories();
}
